* Plan of action for C II

** Summary of project status on revisiting [2022-04-04 Mon]
+ I was reminded of this project by Eduardo's visit
+ I last worked on it in 2021 December - 4 months ago
*** Overview
+ There are 3 parts to project, as I see it:
  1. Observations of C II fluorescent and recombination components
     - SPM spectra of C II 6578 with velocity resolution
     - MUSE spectra of many lines
     - /possibly/ UVES spectra from Eduardo and various from literature
       - H II regions and planetary nebulae
     - PPAK spectra from Manu project
       - this has spatially spectra of the 4267 pure recomb line
       - but data analysis and calibration is more problematic
  2. Observations of the reverse Trapezium shell in [O III] 5007
     - This is a region of radius approx 10 arcsec around th1C, where the [O III] mean velocity is the same as 13CO velocity. Roughly +9 km/s LSR
     - Surrounded by a ring that is bright at 0 to +4 km/s LSR
     - The ring can be seen as peak in the linewidth maps in García-Díaz & Henney 2008
     - The interpretation is that this is where the stellar wind interacts with the ionized gas
       - The back side is a stagnation region, where the ionized gas cannot flow towards us because of the obstacle of the stellar winds
       - The shell is where it is free to flow towards us
     - There is no apparent blueshifted near side of the shell, suggesting that the wind may be free to escape on that side
       - But there is the strange pattern of blue-shifted high velocity flows, first pointed out by Meaburn & Massey, which might be related
  3. Interpretation of the effect of stellar wind on nebula
     - Is it plausible that the wind may be driving the large-scale shell seen in FIR C II lines, as claimed by Pabst et al?
       - Over much of the large-scale nebula shell (0.5 degree scale), especially in the SW, there is a blueshifted component at velocities out to -5 km/s LSR
       - The velocity structure seems a coherent half-shell, returning to the systemic velocity of +8 at the edges
       - Is this the same as one of the Veil components?
         - Not really. The strongest absorption components (vdW 1989) are not shifted by so much from the background cloud: A (+6 km/s) and B (+4 km/s).  Only the much weaker C (-2 km/s) is perhaps similar.
         - Component C is found S of Bar and W of core, so that would make it a good candidate. Also has a large density (2000 to 6500 pc) and small line-of-sight extent (0.1 pc).
         - vdW 2013 has more detail and also includes emission components, but the area covered is quite small compared with the entire shell and does not extend far south enough to the regions with most interesting splitting in C II
         - It turns out that the H I observations are not as useful as they might be, since they include a whole lot of emission and absorption from gas that may be a long way outside the nebula, whereas the C II FIR line is concentrated in a narrow zone of the PDR
       - Starting at Trapezium and extending to the East for a few arcmin, is another partial shell in C II emission, which has a blue-shifted component 



*** Upcoming tasks for individual parts

**** C II observations
The first paper can be just on these

***** TODO Put draft of paper on Overleaf
***** TODO Prepare figures of SPM results
+ Specifically, the comparison of kinematics between [O III] and C II
  + It is somewhat surprising that they are so similar
+ But is this really necessary for the first paper, given that we will not be talking about kinematics

***** TODO Redo the weak lines using the full-resolution cube
+ This is the first 10 sections of the notebook
  + [[file:../notebooks/02-MUSE-6462.ipynb]]

***** TODO Analyze the Manu PPAK data
- I have all the line fluxes and positions, so it should be relatively easy to create some interpolated maps.




***** TODO Find the place where the UV pumping lines should be absorbed
- We are probably going to have to run some Cloudy models
- Find out what the C+ ion fraction is likely to be at the illuminated face as a function of density.
  - We can make maps of the [Ar IV] density form Manu
- Work out the cross section for absorption of the driving lines
  - Why is it that the C II fluorescent lines come from the inner edge, whereas O I fluorescent lines come from the PDR. or at least the bit behind the i-front.
  - [[id:754B51D0-E57F-4870-A1FA-031B8529F62A][What are the relevant pumping lines?]] is the section where I do this
- Do I have a good term diagram for C II anywhere, that has the relevant lines?

**** Nature of the Big Arc
+ *New* [2022-04-05 Tue] I now think that the Big Arc /might/ be illuminated by th2A (*I no longer believe this* [2022-04-08 Fri 08:54])
  + The main evidence for this is that the 7236/7231 ratio is the same (about 0.75) in the Big Arc as near th2A, whereas it is about 0.65 in the Trapezium shell, and 0.55 in the recombination-dominated zones
  + However, HH 202 also has the same ratio, and I don't think *that* is illuminated by th2A, do I?
  + Other evidence against this idea is that the ionization is so high (lots of [O III])
+ There is HI emission from the Big Arc, sort of
  + It is less blueshifted, peaking at V_LSR = -15 km/s, as opposed to -22 km/s for the oiii
  + And the spatial coincidence is not perfect either - it overlaps the Bar a bit in the east
+ Big Arc as the sheath of jets
  + [ ] Where did I last talk about this?
  + There are some high-velocity flows that can be seen in the blue oiii channel maps, which look like corkscrew jets
  + 
** General things to look at
*** Effect of illuminating spectrum
+ We have the comparison between the Trapezium region and the \theta^2 A region for Orion
  + Different lines behave slightly differently:
    + 7236 has broad peak to SW of th2A
      + Region of giant bow in front of HH 204
        + But maybe not related
    + 6578 shows the same but also more extended emission to the E
      + Possibly related th2B?
+ Comparison with other H II regions?
*** What is revealed by the fluorescent distribution of C II in Orion?
+ Interior surface of the warm ionized gas
  + Bounded inside by the shocked stellar wind?
+ Comparison with high-ionization lines
  + [Cl IV] 8045.62
    + Also 7530.80 but that overlaps C II 7530.57
  + [Ar IV] 4740.17
    + Also 4711.37 but that overlaps with He I 4713.14
+ Other fluorescent lines
  + N III 4634
    + We have this with MUSE at poor S/N
    + But also with PPAK
+ Proplyd bow shocks
  + LV1, LV2, etc
+ Kinematics?
  + Are the C II lines good enough s/n to measure this?
  + Yes - see [[file:../notebooks/01-KPNO-6578.py]]
  + Kinematics very similar to [O III]
*** Comparison with other fluorescent lines
+ O I and N I trace the near PDR
+ Si II has a diversity of distributions
  + This is the same electron configuration as C II, but n=3 instead of n=2
    + The wavelengths of equivalent transitions (so with n higher by 1 in Si II) tend to be shorter in Si II than C II by about 30%
    + Si II 4p \to 4d \lambda5041, 5056 is equivalent of C II 3p \to 3d 7231, 7236
    + Si II 4s \to 4p \lambda6347, 6371 is equivalent of C II 3s \to 3p 6578, 6583
    + Si II 4p \to 5s \lambda5958, 5979 is equivalent of C II 3p \to 4s 3919, 3921
    + Si II 5p \to 6d \lambda6818, 6830 is equivalent to C II 4p \to 5d 6257
      + But 6818 is not detected and 6830 overlaps with He I 6827.97
  + We don't seem to detect any of the pure recombination lines of Si II
    + 4f \to 6g at 6240 is same levels as C I 6460 (but not really equivalent, since we should use 1 higher n for Si II), but we do not detect it (presumably because of the low Si abundance)
    + 4d \to 5f at 7849, 7850 is equivalent of C II 4267, but we do not detect it
+ O II might have a fluorescent contribution, which could be relevant to ADF
  + This is treated in detail in
    + [[file:../../Orion-HH/muse-oii-permitted.org][file:~/Dropbox/Orion-HH/muse-oii-permitted.org]] has general description of the project
    + [[file:../../Orion-HH/oii-fluorescence.org][file:~/Dropbox/Orion-HH/oii-fluorescence.org]] has detailed calculation of routes for the fluorescent excitation of the O II V1 lines
    + 

** Atomic structure of C II (and Si II) 

*** Relevant papers
+ [[https://ui.adsabs.harvard.edu/abs/2012MNRAS.426.2318E/abstract][Escalante:2012a]]
  + Excitation of emission lines by fluorescence and recombination in IC 418
  + V. Escalante, C. Morisset and L. Georgiev


*** Ground configuration
+ 5 electrons
+ 1s^2 2s^2 (^{2}S) 2p .^{2}P^o
  + Excitations of this give doublet manifold of excited states 2s^2 n\ell .^{2}L
+ Also, excited core metastable state:
  + 1s^2 2s 2p^2 .^{4}P
  + I think the lines marked as DR come from excited quartet terms
+ And doubly excited core
  + 1s^2 2p^3 .^{2}P^o
  + Has transitions to 1s^2 2s 2p (^{3}P^o) n\ell
    + At least this is what the Atomic Line List says
    + The Escalante paper says 1s^2 2s 2p (^{1}D^o) n\ell (for instance 3p)


*** Relevant excited levels
+ lower \to upper
+ 7231, 7236
  + 3p .^{2}P^o \to 3d .^{2}D
+ 6578, 6583
  + 3s .^{2}S \to 3p .^{2}P^o
+ 6257, 6260
  + 4p .^{2}P^o \to 5d .^{2}D
+ 6460 (recomb)
  + 4f .^{2}F^o \to 6g .^{2}G (L = 4)
+ 4267 (recomb, mainly)
  + 3d .^{2}D \to 4f .^{2}F^o (L = 3)
*** What are the relevant pumping lines?
:PROPERTIES:
:ID:       754B51D0-E57F-4870-A1FA-031B8529F62A
:END:
+ 7231, 7236 can have their upper level (2d) directly pumped from the ground
  + 2p .^{2}P^o \to 3d .^{2}D : 687 \AA
    #+begin_example
          : -LAB-WAVL-ANG-VAC-|-SPC--|TT|--------CONFIGURATION--------|-TERM--|-J_i-J_k-|--A_ki---|-TPF-|--LVL-EN--CM-1---|-REF---|
          :     687.0526        C II  E1         2s2.2p-2s2.3d         2Po-2D  1/2 - 3/2 2.400e+09    24  0.00 - 145549.27 ASD	  
          :     687.3453        C II  E1         2s2.2p-2s2.3d         2Po-2D  3/2 - 5/2 2.880e+09    24 63.42 - 145550.70 ASD
          :     687.3521        C II  E1         2s2.2p-2s2.3d         2Po-2D  3/2 - 3/2 4.810e+08    24 63.42 - 145549.27 ASD
    #+end_example
+ 6578 (3p) should mainly be populated by the same route
  + Cannot be directly from ground (2p), so routes could be
    + 2p -UV*687-> 3d -7231-> 3p -6578-> 3s
    + 2p -UV*636-> 4s -3920-> 3p -6578-> 3s
    + Or 4d, 5s, 5d, etc
  + [X] But also via 4s - need to find details for that line
    + There is a doublet 3919,21
    + Perhaps it is seen in the PPAK data
    + In principle, the 6578 line should be the sum of 7231 plus all the other ways of getting to 3p, of which 3920 is probably the most important, but there may also be 4d to 3p, and then 5s, 5d, etc
+ 4267 has a small fluorescent contribution too
  + upper level is 4f, which we can reach from 5d, which can be reached directly from ground 2p
  + 2p -UV*-> 5d -1.04 micron-> 4f -4267-> 3d -7231-> 3p -6578-> 3s for instance
  + So this route will also be a minor contribution to the 7231 and 6578 lines too
  + I am assuming that 4d is below 4f - need to check that
+ 6460 will have almost no fluorescent contribution since its upper level is 6g
  + Can be reached from 7f, which can be reached from 8d, which can be pumped directly from ground
  + And the cross section for 2p-8d will be much less than for 2p-5d
  + Not to mention that the branching ratios for 8d-7f-6g will also be small
*** Recombination contribution to spectrum
**** Estimate of 4267+ / 6578+ from recombination
***** Estimate based on Escalante:2012a
This is the table of their calculations for IC 418, which should be typical conditions for PNe and H II regions
| Lower-Upper      |   \lambda(À) | I_rec/I_calc | I_calc |  I_obs |  I_rec |
|------------------+--------+------------+-------+-------+-------|
| 3d2D5/2-4f2F9,   | 4267.3 |      0.989 | 59.20 | 57.12 | 58.55 |
| 3s251/2-3p2Pg3/2 | 6578.1 |      0.654 | 42.90 | 53.74 | 28.06 |
| 3s2S1/2-3p 2P°n  | 6582.9 |      0.527 | 26.60 |       | 14.02 |
| 3p-P9/2-3d-D3/2  | 7231.3 |      0.632 | 26.60 | 16.92 | 16.81 |
| 3p2P92-3d2D5/2   | 7236.4 |      0.836 | 43.30 | 46.73 | 36.20 |
| 3p2P%2-3dD3/2    | 7237.2 |      0.632 |  5.30 |  4.89 |  3.35 |
#+TBLFM: $6=$3 $4;f2

+ The last column is the predicted intensity from recombination alone
+ Unfortunately, I don't know if their value for 4267.3 includes the 4267.0 component or not
+ Anyway, they get 4267.3/6578.1 = 58.55/28.06 = 2.1
  + If they included 4267.0 as well, it would be slightly higher
  + But including 6582.9 (unobservable!) would make it lower again
***** Estimate based on Davey:2000a
Effective recombination coefficients (units 1e-14 cm^3/s) for different T (units of 1000 K)
| Transition      | A[nm] | Case |     3.5 |     5.0 |     7.5 |    10.0 |    12.5 |    15.0 |    20.0 |
|-----------------+-------+------+---------+---------+---------+---------+---------+---------+---------|
| 4f(2F°)-3d(?De) | 426.7 | A    | 8.06e+1 | 5.65e+1 | 3.72e+1 | 2.73e+1 | 2.14e+1 | 1.79e+1 | 1.51e+1 |
| -               | -     | B    | 8.12e+1 | 5.70e+1 | 3.75e+1 | 2.76e+1 | 2.17e+1 | 1.81e+1 | 1.53e+1 |
| 3p(2Po)-3s(?Se) | 658.0 | A    | 9.39e+0 | 7.82e+0 | 6.57e+0 | 6.20e+0 | 6.28e+0 | 6.56e+0 | 7.21e+0 |
| -               | -     | B    | 7.19e+1 | 5.50e+1 | 4.04e+1 | 3.29e+1 | 2.88e+1 | 2.67e+1 | 2.67e+1 |
| 3d(2De)-3p(2po) | 723.5 | A    | 2.02e+0 | 1.48e+0 | 1.03e+0 | 7.91e-1 | 6.57e-1 | 5.86e-1 | 5.66e-1 |
| -               | -     | B    | 1.42e+2 | 1.04e+2 | 7.25e+1 | 5.59e+1 | 4.65e+1 | 4.15e+1 | 4.00e+1 |

+ Case A and Case B - which should we use?
+ Intensity ratio is ratio of \alpha / \lambda
  + Calculation for Case B at 1e4 K
    + I(426.7) / I(658.0) = (2.76e+1 / 426.7) / (3.29e+1 / 658.0) = 1.2936
  + Calculation for Case A at 1e4 K
    + I(426.7) / I(658.0) = (2.73e+1 / 426.7) / (6.20e+0 / 658.0) = 6.79
+ [2022-04-13 Wed 14:03] But again, how do we account for the different lines of the multiplet?
  + For 426.7, they are blended together in the observations I am guessing
  + Whereas for 658.0 they would be resolvable were it not for the [N II] line, which masks the 6582.9 component 
** Datasets to use
*** TODO KPNO Orion
+ This has C II 6578
+ [[file:../../../Work/BobKPNO/2004/README]]
 
*** MUSE Orion
+ Pure recomb
  + 6462
+ Added fluorescence
  + 7231 should be uncontaminated
  + 7236 may be contaminated by [Ar IV] 7237.4, but that should be only 2 to 3% of 4740
  + 6578 needs to have the [N II] subtracted
*** PPAK Orion
+ Has very good map of 4267
+ Also 5342 and 6462
*** SPM MES Orion
+ Also has C II 6578 over a wider field than KPNO
  + And possibly deeper
  + But less systematic coverage
* Creating the continuum-subtracted cubes
+ Most analysis is done in notebooks, but we might as well do this here
+ Copy the code over from muse-oii-permitted.org and the wav ranges from the NGC 346 project
** wavsec1 - 5190 to 6260
#+begin_src python :tangle ../scripts//subtract-continuum-wavsec1.py :eval no
  import sys
  import numpy as np
  from astropy.io import fits
  from astropy.wcs import WCS
  from numpy.polynomial import Chebyshev as T
  import itertools

  try:
      DATADIR = sys.argv[1]
      SUFFIX = sys.argv[2]
      OUTDIR = sys.argv[3]
  except IndexError:
      sys.exit(f"Usage: {sys.argv[0]} DATADIR SUFFIX OUTDIR")

  infile = f"muse-hr-data-wavsec1{SUFFIX}.fits"
  hdu = fits.open(f"{DATADIR}/{infile}")["DATA"]
  w = WCS(hdu)
  nwav, ny, nx = hdu.data.shape
  wavpix = np.arange(nwav)

  # Two pairs of adjacent sections for the true continuum

  # Wavelength sections of clean continuum (lots of small sections)
  clean_sections = [
      [4610.0, 4616.0], [4624.0, 4627.0], # between C II, N II, O II
      [4690.0, 4697.0], [4720.0, 4730.0], # between He I and Ar IV
      [4746.0, 4750.0], [4760.0, 4765.0], # between Fe III lines
      [4782.0, 4786.0], [4820.0, 4830.0], # next to Hb
      [4910.0, 4916.0], [5060.0, 5080.0], # to the red
      [5090.0, 5100.0], [5170.0, 5185.0], # to the red
  ]

  cont_slices = []
  for wavs in clean_sections:
      wavs = 1e-10*np.array(wavs)
      _, _, wpix = w.world_to_pixel_values([0, 0], [0, 0], wavs)
      cont_slices.append(slice(*wpix.astype(int)))


  # Use median over each section to avoid weak lines
  cont_maps = np.array([np.median(hdu.data[_, :, :], axis=0) for _ in cont_slices])
  cont_wavpix = np.array([np.median(wavpix[_], axis=0) for _ in cont_slices])
  # Inefficient but simple algorithm - loop over spaxels
  bgdata = np.empty_like(hdu.data)
  for j, i in itertools.product(range(ny), range(nx)):
      # Fit polynomial to BG
      try:
          p = T.fit(cont_wavpix, cont_maps[:, j, i], deg=2)
          # and fill in the BG spectrum of this spaxel
          bgdata[:, j, i] = p(wavpix)
      except:
          bgdata[:, j, i] = np.nan



  for suffix, cube in [
          ["cont", bgdata],
          ["cont-sub", hdu.data - bgdata],
          # ["cont-div", hdu.data/bgdata],
  ]:
      outfile = infile.replace(".fits", f"-{suffix}.fits")
      fits.PrimaryHDU(header=hdu.header, data=cube).writeto(
          f"{OUTDIR}/{outfile}", overwrite=True)
      print(f"Written {outfile}")
#+end_src
* Making some extra figures
+ Most will come from the notebooks.  But there are some that are easier to generate here. In particular if they are based on ones from other projects
+ General figures go in [[file:../figs/]]
+ Figures that will actually be used in the paper go in [[file:../paper/figs]]
** RBG [O I] / [O II] / [O III] image
+ Do the same as I did for Fig 2b of the Raman paper
  + but without the region boxes.
  + Also, adjust the size a bit to match the C II figure
  + and write as a PDF file.

#+name: rgb-limits-oi-oii-oiii
| linesum-O_I-6300-bin001.fits   |   8000 |   150000 |
| linesum-O_II-7318-bin001.fits  |  20000 |  1000000 |
| linesum-O_III-5007-bin001.fits | 200000 | 23000000 |

#+name: star-coords
| tet01 Ori A |  83.8159384 |  -5.3873146 |  50 |
| tet01 Ori B | 83.81713333 | -5.38524722 |  30 |
| tet01 Ori C | 83.81859898 | -5.38968015 | 100 |
| tet01 Ori D | 83.82163535 | -5.38765726 |  50 |
| tet02 Ori A | 83.84542605 | -5.41606033 | 100 |
| tet02 Ori B | 83.86000176 | -5.41688682 |  70 |

#+name: rgb-lupton-clean
#+header: :var TAB=rgb-limits-oi-oii-oiii SUFFIX="oi-oii-oiii" DATADIR="../../dib-scatter-hii/data/orion-muse"
#+header: :var STRETCH=0.3 Q=4 STARS=star-coords HDU="SCALED"
#+begin_src python :results file :return figfile
  import numpy as np
  import matplotlib.pyplot as plt
  from astropy.visualization import make_lupton_rgb
  from astropy.io import fits
  from astropy.wcs import WCS
  import regions as rg
  import seaborn as sns
  sns.set_context("talk")

  # Unpack the channel info from the table
  [rf, r1, r2], [gf, g1, g2], [bf, b1, b2] = TAB

  def load_and_scale_image(fn, v1, v2, ihdu=HDU):
      data = fits.open(f"{DATADIR}/{fn}")[ihdu].data
      return (data - v1) / (v2 - v1)


  w = WCS(fits.open(f"{DATADIR}/{rf}")[HDU].header)

  image_r = load_and_scale_image(rf, r1, r2)
  image_g = load_and_scale_image(gf, g1, g2)
  image_b = load_and_scale_image(bf, b1, b2)
  image = make_lupton_rgb(image_r, image_g, image_b, stretch=STRETCH, Q=Q)

  figfile = f"../figs/rgb-lupton-clean-{SUFFIX}.pdf"
  fig, ax = plt.subplots(
      figsize=(11, 9),
      subplot_kw=dict(projection=w),
  )
  ax.imshow(image)
  for _, ra, dec, size in STARS:
      ax.scatter(ra, dec, transform=ax.get_transform("icrs"), s=0.6*size, ec="yellow", fc="none")
  ax.set(xlabel="RA (J2000)", ylabel="Dec (J2000)")

  fig.tight_layout(rect=[0.08, 0.07, 1.0, 1.0])
  fig.savefig(figfile)
#+end_src

#+RESULTS: rgb-lupton-clean
[[file:../figs/rgb-lupton-clean-oi-oii-oiii.pdf]]

#+name: cii-723x-ratio
#+header: :var STARS=star-coords
#+begin_src python :results file :return figfile
  import numpy as np
  import matplotlib.pyplot as plt
  from astropy.visualization import make_lupton_rgb
  from astropy.io import fits
  from astropy.wcs import WCS
  import regions as rg
  import seaborn as sns
  sns.set_context("talk")

  hdu_ratio = fits.open("../data/orig-muse/ratio-723X-6563-multibin.fits")[0]
  w = WCS(hdu_ratio.header)

  figfile = f"../figs/ratio-cii723x-ha-multibin.pdf"

  fig, ax = plt.subplots(
      figsize=(11, 9),
      subplot_kw=dict(projection=w),
  )
  im = ax.imshow(
      hdu_ratio.data,
      vmin=0.0, vmax=0.004,
      cmap="gray",
  )
  for _, ra, dec, size in STARS:
      ax.scatter(ra, dec, transform=ax.get_transform("icrs"), s=0.6*size, ec="black", fc="yellow")

  ax.set(xlabel="RA (J2000)", ylabel="Dec (J2000)")
  ax.set_title(
      "(C II λλ7231 + 7236) / Hα λ6563", 
      pad=12,
      y=0.0,
      fontweight="bold",
      color="w",
  )
  fig.tight_layout(rect=[0.08, 0.07, 1.0, 1.0])
  fig.savefig(figfile)
#+end_src

#+RESULTS: cii-723x-ratio
[[file:../figs/ratio-cii723x-ha-multibin.pdf]]


* Previous notes from other projects
These are just copied verbatim here.

Also, general notes on permitted lines can be found in:
+ [[file:../../Orion-HH/muse-oii-permitted.org]]
+ [[file:../../Metal-Permitted/metal-permitted.org]]



** orion-muse.org
*** Random thoughts on permitted lines
:LOGBOOK:
CLOCK: [2017-01-05 Thu 13:05]--[2017-01-09 Mon 19:46] => 102:41
:END:
+ Good discussion in Sharpee et al 2004
  + Turns out that the C II 7231, 7236 lines are already expected to be 50% fluorescence
    + At least according to Grandi (1976)
    + This is multiplet V3
  + Description of morphology of the fluorescent contribution is hidden away in [[id:347AC3EE-D131-4BEF-9A94-71DC9FFFD199][{10/10} Perform line extraction, fuzzing, binning, multimapping all on linux server]]
  + The best C II line is V6 4267, which we don't have
  + The pure recomb lines that we /do/ have are
    + 4620.11 V17.08 - clean bit of spectrum but very weak
    + 4802.740 - messy blend with N II and possibly [Co II]
    + 5342.40 V17.06 - clean but weak
    + 6151.43 V16.04 - stronger than the others, more or less clean, except for O I 6156 on the red side
    + 6461.95 V17.04 - strongest so far and clean
    + 7519.49 - not in Sharpee, sky contam but subtractable
  + So best bet seems to be 6461.95
*** DONE [#A] [10/10] Perform line extraction, fuzzing, binning, multimapping all on linux server
CLOSED: [2015-11-09 Mon 19:46]
:PROPERTIES:
:ID:       347AC3EE-D131-4BEF-9A94-71DC9FFFD199
:END:
:LOGBOOK:
- Note taken on [2015-11-09 Mon 19:46] \\
  This took forever!
:END:
...
*Lots of steps*
...
9. Do multibin combination for the ratios at constant s/n
   - [X] Pilot study for selected ratios.  Highlights are:
     - C II 7236 / H\alpha 6563 - shows wonderful swirls, presumably where thet fluorescent excitation of the C II line is highest, which should trace the inner edge of dense ionized gas in the nebula.  This has peaks (from inside to outside) at the LV bowshocks; at the *Ney-Allen Nebula*; at the filament behind LV6; /possibly/ the 177-341 bowshock; in a *270 degree shell* that starts in front of 177-341 and curves round to W past 159-350 shocks, then runs NW parallel to the SW lane (and yes, that is an extinction feature, the superposition may be conicidental), then bends to the E to run along just inside the high-ionization inner arm of the E-W bar (of course the appearance of a 270 deg shell may be illusory); then the E side of the *Big Arc*, which is the largest scale feature (to the W it becoes less prominent, which coincides in PA with where the inner 270 deg shell gets brighter - maybe it is blocking it); then finally, around \theta2A.  There is also a dip at the Bright Bar i-front, which must be due the C++/C+ transition
   
*** Extract from basic-line-list.tab
+ /Note added [2021-11-24 Wed]/
  + I have included other lines that are within 1 or 2 Angstrom of the C II lines
#+name: cii-line-list
| Ion     | Class |     wav0 | strength | blue cont | red cont | comment                      |
|---------+-------+----------+----------+-----------+----------+------------------------------|
| C II    | P     |  4620.11 |        6 |         1 |        1 | *** also 4620.26, pure recom |
| C II    | P     | 4802.740 |        5 |         1 |        0 | *** blend but pure recom     |
| N II    | P     | 4803.287 |        4 |         1 |        1 | blend [Co II] 4802.36        |
| C II    | P     |  5121.82 |        7 |         1 |        1 | ***                          |
| C II    | P     |  5342.40 |        6 |         0 |        1 | *** V17.06 pure recom        |
| C II    | P     |  5889.78 |        4 |         1 |        0 | Na I sky blend, V5           |
| C II    | P     |  6151.43 |        5 |         1 |        0 | V16.04, pure recomb          |
| O I     | L     |  6155.98 |        6 |         0 |        1 | * blend with Ni II 6157.42   |
| C II    | P     |  6257.18 |        7 |         1 |        0 | *** V10.03 + O I ?           |
| C II    | P     |  6259.56 |        7 |         0 |        1 | *** V10.03, pure recomb      |
| C II    | P     |  6461.95 |        6 |         1 |        1 | V17.04 Pure recomb           |
| C II    | P     |  6578.05 |        5 |         1 |        0 | Blue 6583.45 dominates       |
| [N II]  | L     |  6583.45 |        2 |         1 |        1 |                              |
| C II    | D     |  6779.94 |        7 |         1 |        0 | *** +6780.60 DIELEC          |
| C II    | D     |  6787.22 |        7 |         1 |        1 | ***                          |
| C II    | P     |  6812.28 |        7 |         0 |        1 | *** or [Ni II] 6813.57 ?     |
| C II    | P     |  7231.34 |        3 |         1 |        0 | V3 - 50% fluorescence        |
| C II    | P     |  7236.42 |        3 |         0 |        1 | 7236.42 + 7237.17            |
| O II    | P     | 7369.029 |        6 |         1 |        0 | blend C II 7370.0            |
| C II    | P     |  7519.49 |        6 |         1 |        0 | Plus Sky at 7524             |
| [Cl IV] | U     |  7530.80 |        5 |         0 |        1 | blend C II 7530.57           |







** muse-oii-permitted.org
*** TODO Permitted lines
+ Extract O II and C II lines from MUSE
+ For the O II lines, we need to isolate the 4649 blend
+ For C II pure recomb lines 
  + We have 4620 supposedly ?!
    + Very weak and there may be another line at 4621
  + Also 4803 but blended with N II and [Co II]
  + 5342.40 - very weak
  + 6151.43 - might be good
  + 6461.96 - weak but should be clear
    + This is definitely the best bet for C II lines
    + Escalante:2012a have it being all recombination
    + Whereas 7231 and 7236 are 20 to 40% fluorescent in IC 418
+ N II lines
  + These are generally weak and must be a mixture of recombination and fluorescence
+ Si II lines
  + These are much stronger, also mixture
+ More O II lines from Manu/Adal
  + 4609, 4610 - Escalante:2012a says is 100% recombination
    + Terms are in LK coupling scheme
      + 3d 2D5/2–4f F[4]o7/2
      + 3d 2D3/2–4f F[2]o5/2
    + Unfortunately, there is an [Fe III] line at 4607
    + Also N II 4607 but that is weaker
    + 4607 to 4610 are blended in Manu and MUSE
    + The O II lines are well separated from [Fe III] in Adal
    + Discussed further below
  + 4596
+ [ ] Excitation of O II V1
  + Multiplet (quartet) is 3s ^4P \to 3p ^4D
    + Storey:2017a has more rigorous terminology
    + But backwards: UPPER \to LOWER
    + 2s^{2} 2p^{2}(.^{3}P) 3p .^{4}D_{o} \to  2s^{2} 2p^{2}(.^{3}P) 3s .^{4}P_{e}
    + ~2s22p2(3P)3p 4Do    -   2s22p2(3P)3s 4Pe~
    + E.g., 4649.13 is index 8790
  + Ground state is 2p3 ^4S
    + Resonant absorption 2p3 ^4S \to 3d ^4P (429.650 \to 429.716 \AA)
      + so that is 2.12 Rydbergs
    + Followed by decay to 3p terms
    + Need to make a diagram and work out if it is feasible
  + Velocity gradients in Big Arc will tend to make fluorescence more efficient
  + Interestingly, the analogous N I multiplet is at 8680-8719
    + N I and O II are identical in electron configuration
    + We see all these lines nicely in the MUSE data
    + They are all at least 95% fluoresced
    + [ ] We could look at the equivalent of the 3d-4f lines in N I
+ Case of the 3d-4f lines
  + These should not have a fluorescent component
    + /except that maybe they might if intercombination lines are important/
  + But they give the same abundances as the other lines (in Eduardo HH 529 data)
  + Strongest lines:
    + 4303.8: I \approx 0.63e-4 Hb  (Escalante:2013a)
      + Compare with 4649 \approx 6.7e-4 Hb
        + ODell:2010a have 4959/Hb = 0.7 to 1.0 in slits 10 and 11, which cover area of Adal's slit 6
        + Adal has 4649/4959 = 10 \to 12 times 1e-4
        + Eduardo (cut 2) has I(4649.13) = 11.4 in nebula and 24 in shock !!
      + Eduardo 4959/Hb in cut 2
        + 1.15 in nebula
        + 1.67 in shock
      + Seen in Manu data - about 5 times weaker than 4317 and 4320 (3s ^4P - 3p ^4P)
        + Which are themselves about 4 times weaker than V1
        + E.g., Manu has 4649 = 1.13 x cont
        + I(4304) = 0.01 x cont, so 13 x weaker than 4649 => I(4304) = 0.77 1e-4 I(Hb)
        + Within the errors, this is consistent with Escalante predicted, especially if we add in the 4303.5 contribution: 0.09 + 0.63 = 0.72
      + Observed in Eduardo: I = 2.0 (cut 3) and 2.1 (cut 2 neb), and 4.6 (cut 2 shock) !!!
    + 4277 complex
      + Strongest component: 4275.5 with predicted I = 0.84
        + Blended with [Fe II] 4276.84 in Manu
        + Observed in Eduardo with observed I = 1.6
    + 4609.3: predicted I \approx 0.66e-4 Hb  (Escalante:2013a)
      + Also, weaker component at 4610.2
      + Seen in Manu, but blend with [Fe III] 4607
      + Very well isolated in Adal: I(4609) = 1e-4 I(4959)
      + So this has observed intensity that maybe is slightly higher than predicted (by about 30%)
+ What states can we have
  + 3 outer electrons
  + Ground state is 2p^3 ^4S
    + 2S+1 = 4 => S = 3/2 so all 3 spins are aligned
    + L=0 so J = 3/2
  + Pumped state: one electron goes from 2p \to 3d
    + L = 0 \to 1 for E1 transition so must be a ^4P state
    + In fact *only* ^4P levels can be directly pumped from ground
      + At least I would have thought, although Escalante also mention ^4S \to ^4D transition, which has \Delta L = 2, so must be quadrupole
    + So 2p^2 3d ^4P has L=1, S=3/2, J= 5/2, 3/2, 1/2
  + If we pump the 3d .^{4}P level then we need the transition
    + 3d .^{4}P_{e} \to 3p .^{4}D_{o} in order to populate the upper level of V1
    + Storey has the following components:
      |  IND |     wav | 2JI | 2JF | Other         | Manu  |
      |------+---------+-----+-----+---------------+-------|
      | 8494 | 3864.13 |   1 |   1 | Si II 3863    | Blend |
      | 8493 | 3872.44 |   1 |   3 | [Ne III] 3869 |       |
      | 8515 | 3874.09 |   3 |   1 | He I 3878     |       |
      | 8514 | 3882.45 |   3 |   3 | H I 3889      | ?     |
      | 8566 | 3893.52 |   5 |   3 | H I 3889      |       |
      | 8513 | 3896.30 |   3 |   5 |               | faint |
      | 8565 | 3907.45 |   5 |   5 |               | yes   |
      | 8564 | 3926.58 |   5 |   7 | He I 3927     |       |
    + Unfortunately, most will be blended with other lines
  + We should also get another route down via 3p .^{4}S:
    + 3d .^{4}P_{e} \to 3p .^{4}S_{o} followed by 3p .^{4}S_{o} \to 3s .^{4}P_{e}
      + which ends at same lower level as V1
    + 3d .^{4}P_{e} \to 3p .^{4}S_{o} or ~2s22p2(3P)3d 4Pe    -   2s22p2(3P)3p 4So~
      |  IND |     wav | 2JI | 2JF | Other                    | Manu   | MUSE   | Adal              |
      |------+---------+-----+-----+--------------------------+--------+--------+-------------------|
      | 8489 | 4890.86 |   1 |   3 | [Fe II] 4890             | Blend? | Blend? | weak but resolved |
      | 8507 | 4906.83 |   3 |   3 | [Fe II] 4905             | Blend? | Blend  | Weak              |
      | 8559 | 4924.53 |   5 |   3 | He I 4922, [Fe III] 4925 | Blend? | No     | Possibly          |
    + 3p .^{4}S_{o} \to 3s .^{4}P_{e} or ~2s22p2(3P)3p 4So    -   2s22p2(3P)3s 4Pe~
      |  IND |     wav | 2JI | 2JF | Other       | Manu |
      |------+---------+-----+-----+-------------+------|
      | 8730 | 3712.74 |   3 |   1 | H I 3712    | No   |
      | 8729 | 3727.32 |   3 |   3 | [O II] 3726 | No   |
      | 8728 | 3749.48 |   3 |   5 | H I 3750    | No   |
    + So this is the *cursed multiplet* - no chance of ever seeing it
